# Generated by Django 5.2.1 on 2025-05-12 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название атаки')),
                ('cve', models.CharField(blank=True, max_length=50, null=True, verbose_name='CVE')),
                ('description', models.TextField(blank=True, verbose_name='Описание атаки')),
                ('recommended_measures', models.TextField(blank=True, verbose_name='Рекомендованные меры')),
            ],
            options={
                'verbose_name': 'Тип атаки',
                'verbose_name_plural': 'Типы атак',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_date', models.DateField(verbose_name='Дата выявления угрозы')),
                ('source_ip', models.GenericIPAddressField(verbose_name='Источник угрозы')),
                ('destination_ip', models.GenericIPAddressField(verbose_name='Адрес назначения')),
                ('detection_tool', models.CharField(choices=[('WAF', 'WAF'), ('IPS', 'IPS'), ('EDR', 'EDR'), ('SIEM', 'SIEM'), ('Other', 'Другое')], max_length=50, verbose_name='Средство обнаружения')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('methods', models.CharField(blank=True, max_length=200, verbose_name='Методы атаки')),
                ('protocols_ports', models.CharField(blank=True, max_length=200, verbose_name='Протоколы и порты')),
                ('risk_assessment', models.CharField(blank=True, max_length=50, verbose_name='Оценка риска')),
                ('potential_impact', models.TextField(blank=True, verbose_name='Потенциальные последствия')),
                ('payload', models.TextField(blank=True, verbose_name='Payload')),
                ('response_actions', models.TextField(blank=True, verbose_name='Реагирование на инцидент')),
                ('attack_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.attacktype', verbose_name='Тип угрозы')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
