# Generated by Django 5.2.1 on 2025-06-11 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
        migrations.RemoveField(
            model_name='attacktype',
            name='cve',
        ),
        migrations.RemoveField(
            model_name='attacktype',
            name='recommended_measures',
        ),
        migrations.RemoveField(
            model_name='report',
            name='payload',
        ),
        migrations.AddField(
            model_name='attacktype',
            name='data',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attacktype',
            name='detection_tool',
            field=models.CharField(choices=[('WAF', 'WAF'), ('IPS', 'IPS'), ('EDR', 'EDR'), ('SIEM', 'SIEM'), ('Other', 'Другое')], default=1, max_length=10, verbose_name='Средство обнаружения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attacktype',
            name='methods',
            field=models.CharField(default=1, max_length=200, verbose_name='Методы атаки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attacktype',
            name='potential_impact',
            field=models.TextField(blank=True, verbose_name='Потенциальные последствия'),
        ),
        migrations.AddField(
            model_name='attacktype',
            name='protocols_ports',
            field=models.CharField(blank=True, max_length=100, verbose_name='Протоколы и порты'),
        ),
        migrations.AddField(
            model_name='attacktype',
            name='response_actions',
            field=models.TextField(blank=True, verbose_name='Реагирование на инцидент'),
        ),
        migrations.AddField(
            model_name='attacktype',
            name='risk_assessment',
            field=models.CharField(choices=[('Критическая', 'Критическая'), ('Высокая', 'Высокая'), ('Средняя', 'Средняя'), ('Низкая', 'Низкая')], default='Низкая', max_length=12, verbose_name='Критичность'),
        ),
        migrations.AddField(
            model_name='report',
            name='cve',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='data_or_payload',
            field=models.TextField(blank=True, verbose_name='Дата или payload'),
        ),
        migrations.AddField(
            model_name='report',
            name='host',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='attack_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.attacktype', verbose_name='Тип угрозы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='detection_date',
            field=models.CharField(verbose_name='Дата и время выявления угрозы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='detection_tool',
            field=models.CharField(choices=[('WAF', 'WAF'), ('IPS', 'IPS'), ('EDR', 'EDR'), ('SIEM', 'SIEM'), ('Other', 'Другое')], max_length=10, verbose_name='Средство обнаружения'),
        ),
        migrations.AlterField(
            model_name='report',
            name='risk_assessment',
            field=models.CharField(max_length=120, verbose_name='Критичность'),
        ),
        migrations.AddField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reports.organization', verbose_name='Организация'),
            preserve_default=False,
        ),
    ]
