# Generated by Django 5.2.1 on 2025-05-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование организации')),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='detection_tool',
            field=models.CharField(choices=[('WAF', 'WAF'), ('IPS', 'IPS'), ('Other', 'Другое')], max_length=50, verbose_name='Средство обнаружения'),
        ),
    ]
