# Generated by Django 5.2.1 on 2025-06-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_organization_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacktype',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
