# Generated by Django 5.2.1 on 2025-06-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_attacktype_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='detection_date',
            field=models.DateTimeField(verbose_name='Дата и время выявления угрозы'),
        ),
    ]
