# Generated by Django 5.2.1 on 2025-06-24 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.pattern', verbose_name='Шаблон'),
        ),
    ]
