# Generated by Django 5.2.1 on 2025-05-14 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.organization', verbose_name='Организация'),
            preserve_default=False,
        ),
    ]
