# Generated by Django 5.2.1 on 2025-06-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_organization_alter_report_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='attack_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название атаки'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание атаки'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='detection_tool',
            field=models.CharField(blank=True, choices=[('WAF', 'WAF'), ('IPS', 'IPS'), ('EDR', 'EDR'), ('SIEM', 'SIEM'), ('Other', 'Другое')], max_length=10, null=True, verbose_name='Средство обнаружения'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='methods',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Методы атаки'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='potential_impact',
            field=models.TextField(blank=True, null=True, verbose_name='Потенциальные последствия'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='response_actions',
            field=models.TextField(blank=True, null=True, verbose_name='Реагирование на инцидент'),
        ),
        migrations.AlterField(
            model_name='report',
            name='risk_assessment',
            field=models.CharField(choices=[('Критическая', 'Критическая'), ('Высокая', 'Высокая'), ('Средняя', 'Средняя'), ('Низкая', 'Низкая')], default='Низкая', max_length=12, verbose_name='Критичность'),
        ),
    ]
