# Generated by Django 5.2.1 on 2025-05-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterField(
            model_name='report',
            name='detection_tool',
            field=models.CharField(choices=[('WAF', 'WAF'), ('IPS', 'IPS'), ('EDR', 'EDR'), ('SIEM', 'SIEM'), ('Other', 'Другое')], max_length=10, verbose_name='Средство обнаружения'),
        ),
        migrations.AlterField(
            model_name='report',
            name='risk_assessment',
            field=models.CharField(choices=[('Критическая', 'Критическая'), ('Высокая', 'Высокая'), ('Средняя', 'Средняя'), ('Низкая', 'Низкая')], default='Низкая', max_length=12, verbose_name='Критичность'),
        ),
    ]
