# Generated by Django 5.2.1 on 2025-07-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_pattern_attack_type_alter_pattern_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-21'),
            preserve_default=False,
        ),
    ]
