# Generated by Django 5.2.1 on 2025-05-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='detection_date',
            field=models.DateTimeField(verbose_name='Дата и время выявления угрозы'),
        ),
    ]
