# Generated by Django 5.2.1 on 2025-10-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
    ]
