# Generated by Django 5.2.1 on 2025-05-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_detection_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attacktype',
            name='recommended_measures',
        ),
    ]
