# Generated by Django 5.2.1 on 2025-07-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username_ru',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
